server:
  # 服务端口号
  port: 8085
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: service-zuul
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://localhost:8081/eureka
zuul:
  routes:
    # 设置服务a 路径名称 随便起
    service-a:
      path: /service-a/**
      #这里写a服务的注册名字
      serviceId: service-objcat-a
    # 设置服务b 路径名称 随便起
    service-b:
      path: /service-b/**
      # 这里写b服务的注册名字
      serviceId: service-objcat-b
# 避免响应时间长触发熔断器
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000